permalink: /:year/:title
auto: true
server: true
pygments: true
baseurl: /pyoperators
package: PyOperators
meta_keywords: Pierre Chanial, Nicolas Barbey, Inverse problem, Signal Processing, High-performance computing, HPC, Python, Operator, Linear Operator, Simulators, Acquisition models, Astrophysics
menu: <a href="http://pchanial.github.com/tamasis-map">Tamasis/PACS</a>
version_stable: 0.2
